version: '3.7'

services:
  app:
    environment:
      - SECRET_KEY=ijvvm@q#bf)*2l=ki4oe)(1)pe6^n&-jyheae=bzcdl3xm%pc0
      - VIRTUAL_HOST=localhost # temporary
      - ALLOWED_HOSTS=localhost # temporary
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && uwsgi ./config/uwsgi.ini"
  nginx-proxy:
    build: nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
