version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=starnet
      - POSTGRES_PASSWORD=starnet
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: ./app
    environment:
      - DATABASE_NAME=starnet
      - DATABASE_USER=starnet
      - DATABASE_PASSWORD=starnet
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    volumes:
      - web-media:/app/media/
      - web-staticfiles:/app/staticfiles/

volumes:
  db-data:
  web-media:
  web-staticfiles:
