# Generated by Django 3.1 on 2021-02-25 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last request to the service'),
            preserve_default=False,
        ),
    ]
