# Generated by Django 3.1 on 2021-02-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='full name'),
        ),
    ]
